coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: js
      paths:
        - js/
      statuses:
        - type: project
          target: 100%
          threshold: 10%
    - name: dotnet
      paths:
        - dotnet/Math.Test
      statuses:
        - type: project
          target: auto
          threshold: 10%