coverage:
  status:
    project:
      default: false
      js:
        target: 100%
        threshold: 10%
        paths:
          - js/
      dotnet:
        target: auto
        threshold: 10%
        paths:
          - dotnet/
    patch:
      default: false